version: '3'
services:
  api:
    build: 
      context: .
      dockerfile: ./api/python/docker/Dockerfile
    tty: true
    volumes:
      - ./api/python/src:/app
    ports:
      - 8080:8080
    depends_on:
      - db

  db:
    image: mysql:8.4
    environment:
      - MYSQL_DATABASE=sample
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pass
      - MYSQL_ROOT_PASSWORD=pass
      - TZ=Asia/Tokyo
    ports:
      - 3306:3306
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
      - ./db/conf:/etc/mysql/conf.d/:ro
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:       