[package]
name = "rest_api"
version = "0.1.0"
edition = "2021"

[dependencies]
dotenv = "0.15.0"
mysql = "25.0.1"
rocket = { version = "0.5.1", features = ["json"] }
rocket_contrib = "0.4.11"
serde = "1.0.210"
serde_json = "1.0.128"
